INSERT INTO market_agents(id,name,strategy_type,strategy_version,default_config_json,enabled)
VALUES ('ai-technical-v4','AI Technical V4','llm','AI_TECHNICAL_V4','{"provider":"ollama","model":"qwen2.5:0.5b","promptVersion":"MARKET_AI_AGENT_V4","temperature":0.1,"decisionInterval":5,"timeoutMs":30000,"maxRetries":1,"signalEngineVersion":"SIGNAL_ENGINE_V1","signalConfigVersion":"SIGNAL_CONFIG_V1","positionEngineVersion":"POSITION_ENGINE_V1"}',1);
INSERT INTO market_ai_agent_configs(agent_id,provider,model,prompt_version,temperature,decision_interval,timeout_ms,max_retries)
VALUES ('ai-technical-v4','ollama','qwen2.5:0.5b','MARKET_AI_AGENT_V4',0.1,5,30000,1);
ALTER TABLE market_ai_decisions ADD COLUMN lifecycle_action TEXT;
CREATE TABLE market_trade_lifecycles(id TEXT PRIMARY KEY,experiment_id TEXT NOT NULL REFERENCES market_experiments(id) ON DELETE CASCADE,agent_id TEXT NOT NULL,asset TEXT NOT NULL,lifecycle_index INTEGER NOT NULL,opened_at TEXT NOT NULL,closed_at TEXT,entry_price REAL NOT NULL,average_entry_price REAL NOT NULL,exit_price REAL,initial_exposure_pct REAL NOT NULL,max_exposure_pct REAL NOT NULL,holding_candles INTEGER NOT NULL,realized_pnl REAL NOT NULL,realized_pnl_pct REAL NOT NULL,mfe_pct REAL NOT NULL,mae_pct REAL NOT NULL,exit_efficiency_pct REAL,profit_giveback_pct REAL NOT NULL,entry_reason_code TEXT,exit_reason_code TEXT,status TEXT NOT NULL CHECK(status IN ('OPEN','CLOSED','ABORTED')),reentry INTEGER NOT NULL CHECK(reentry IN(0,1)),engine_version TEXT NOT NULL,UNIQUE(experiment_id,agent_id,lifecycle_index));
CREATE TABLE market_position_events(id INTEGER PRIMARY KEY AUTOINCREMENT,lifecycle_id TEXT NOT NULL REFERENCES market_trade_lifecycles(id) ON DELETE RESTRICT,decision_id INTEGER REFERENCES market_decisions(id) ON DELETE RESTRICT,timestamp TEXT NOT NULL,action TEXT NOT NULL,previous_exposure_pct REAL NOT NULL,target_exposure_pct REAL NOT NULL,new_exposure_pct REAL NOT NULL,signal_bias TEXT,confidence REAL,reason_code TEXT,risk_result TEXT NOT NULL);
CREATE TABLE market_position_metrics(experiment_id TEXT NOT NULL REFERENCES market_experiments(id) ON DELETE CASCADE,agent_id TEXT NOT NULL,closed_trades INTEGER NOT NULL,winning_trades INTEGER NOT NULL,losing_trades INTEGER NOT NULL,average_holding_candles REAL NOT NULL,median_holding_candles REAL NOT NULL,average_mfe_pct REAL NOT NULL,average_mae_pct REAL NOT NULL,average_exit_efficiency_pct REAL,average_profit_giveback_pct REAL NOT NULL,rapid_reentry_count INTEGER NOT NULL,rapid_exit_count INTEGER NOT NULL,reentry_count INTEGER NOT NULL,average_entry_exposure_pct REAL NOT NULL,average_max_exposure_pct REAL NOT NULL,invalid_position_action_count INTEGER NOT NULL,flat_sell_attempt_count INTEGER NOT NULL,redundant_exit_count INTEGER NOT NULL,engine_version TEXT NOT NULL,PRIMARY KEY(experiment_id,agent_id));
CREATE INDEX idx_market_lifecycle_experiment ON market_trade_lifecycles(experiment_id,agent_id);
CREATE INDEX idx_market_position_events_lifecycle ON market_position_events(lifecycle_id);
