CREATE TABLE market_hold_diagnostic_runs (
  id TEXT PRIMARY KEY,
  experiment_id TEXT NOT NULL REFERENCES market_experiments(id) ON DELETE CASCADE,
  agent_id TEXT NOT NULL REFERENCES market_agents(id),
  engine_version TEXT NOT NULL,
  config_json TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('running','completed','failed')),
  total_ai_calls INTEGER NOT NULL DEFAULT 0,
  total_holds INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  UNIQUE(experiment_id, agent_id, engine_version)
);

CREATE TABLE market_hold_diagnostics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id TEXT NOT NULL REFERENCES market_hold_diagnostic_runs(id) ON DELETE CASCADE,
  decision_id INTEGER NOT NULL REFERENCES market_decisions(id) ON DELETE CASCADE,
  candle_index INTEGER NOT NULL,
  timestamp TEXT NOT NULL,
  session_id TEXT NOT NULL,
  session_phase TEXT NOT NULL,
  position_state TEXT NOT NULL CHECK(position_state IN ('FLAT','LONG')),
  current_exposure_pct REAL NOT NULL,
  confidence REAL,
  confidence_bucket TEXT NOT NULL,
  reason_code TEXT NOT NULL,
  reason TEXT NOT NULL,
  price REAL NOT NULL,
  ema_9 REAL,
  ema_21 REAL,
  vwap REAL,
  rsi_14 REAL,
  atr_14 REAL,
  relative_volume REAL,
  distance_from_vwap_atr REAL,
  ema_spread_atr REAL,
  trend TEXT NOT NULL,
  momentum TEXT NOT NULL,
  volatility TEXT NOT NULL,
  location TEXT NOT NULL,
  vwap_position TEXT NOT NULL,
  trigger_reason TEXT NOT NULL,
  conflict_signature TEXT,
  rsi_bucket TEXT NOT NULL,
  relative_volume_bucket TEXT NOT NULL,
  vwap_distance_bucket TEXT NOT NULL,
  ema_spread_bucket TEXT NOT NULL,
  forward_1 REAL,
  forward_5 REAL,
  forward_10 REAL,
  mfe_1 REAL,
  mfe_5 REAL,
  mfe_10 REAL,
  mae_1 REAL,
  mae_5 REAL,
  mae_10 REAL,
  quality TEXT NOT NULL CHECK(quality IN ('GOOD_HOLD','POTENTIAL_MISSED_OPPORTUNITY','POTENTIAL_LATE_REDUCTION','INCONCLUSIVE')),
  quality_context TEXT NOT NULL,
  UNIQUE(run_id, decision_id)
);

CREATE INDEX idx_market_hold_runs_experiment ON market_hold_diagnostic_runs(experiment_id, agent_id);
CREATE INDEX idx_market_hold_diagnostics_quality ON market_hold_diagnostics(run_id, quality, position_state);
CREATE INDEX idx_market_hold_diagnostics_reason ON market_hold_diagnostics(run_id, reason_code);
