import { useState, type FormEvent } from "react";
import type { KnowledgeArea, Project, ResearchInput, ResearchItem, ResearchKind, ResearchStatus, StudyRoadmap } from "../../types";
import { RecordEditorDialog } from "../core/RecordEditorDialog";

const inputOf = (item?: ResearchItem | null): ResearchInput => item ? { id: item.id, title: item.title, domain: item.domain, objective: item.objective, description: item.description, kind: item.kind, status: item.status, impact: item.impact, knowledgeNodeId: item.knowledgeNodeId, roadmapId: item.roadmapId, roadmapTopicId: item.roadmapTopicId, projectId: item.projectId } : { id: crypto.randomUUID(), title: "", domain: "", objective: "", description: "", kind: "research", status: "planned", impact: "", knowledgeNodeId: null, roadmapId: null, roadmapTopicId: null, projectId: null };

export function ResearchEditor({ item, knowledge, projects, roadmaps, onCancel, onSave }: { item?: ResearchItem | null; knowledge: KnowledgeArea[]; projects: Project[]; roadmaps: StudyRoadmap[]; onCancel: () => void; onSave: (input: ResearchInput) => Promise<void> }) {
  const [form, setForm] = useState(() => inputOf(item));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const topics = roadmaps.find((roadmap) => roadmap.id === form.roadmapId)?.stages.flatMap((stage) => stage.topics) ?? [];
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.title.trim()) { setError("Informe o título da pesquisa."); return; } setBusy(true); try { await onSave({ ...form, title: form.title.trim() }); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); setBusy(false); } }
  return <RecordEditorDialog eyebrow="MAPA STARK // PESQUISA" title={item ? `Editar ${item.title}` : "Nova pesquisa"} busy={busy} error={error} onCancel={onCancel} onSubmit={submit}>
    <label>Título<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Domínio<input value={form.domain} onChange={(event) => setForm({ ...form, domain: event.target.value })} /></label>
    <label>Tipo<select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value as ResearchKind })}><option value="research">Pesquisa</option><option value="study">Estudo</option><option value="project">Projeto experimental</option></select></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as ResearchStatus })}><option value="planned">Planejada</option><option value="active">Ativa</option><option value="paused">Pausada</option><option value="completed">Concluída</option></select></label>
    <label className="record-editor__wide">Objetivo<textarea rows={2} value={form.objective} onChange={(event) => setForm({ ...form, objective: event.target.value })} /></label><label className="record-editor__wide">Descrição<textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label>
    <label>Impacto<input value={form.impact} onChange={(event) => setForm({ ...form, impact: event.target.value })} /></label><label>Conhecimento<select value={form.knowledgeNodeId ?? ""} onChange={(event) => setForm({ ...form, knowledgeNodeId: event.target.value || null })}><option value="">Sem vínculo</option>{knowledge.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label>
    <label>Roadmap<select value={form.roadmapId ?? ""} onChange={(event) => setForm({ ...form, roadmapId: event.target.value || null, roadmapTopicId: null })}><option value="">Sem vínculo</option>{roadmaps.map((roadmap) => <option key={roadmap.id} value={roadmap.id}>{roadmap.name}</option>)}</select></label><label>Tópico<select value={form.roadmapTopicId ?? ""} disabled={!form.roadmapId} onChange={(event) => setForm({ ...form, roadmapTopicId: event.target.value || null })}><option value="">Sem vínculo</option>{topics.map((topic) => <option key={topic.id} value={topic.id}>{topic.name}</option>)}</select></label>
    <label>Projeto<select value={form.projectId ?? ""} onChange={(event) => setForm({ ...form, projectId: event.target.value || null })}><option value="">Sem vínculo</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
  </RecordEditorDialog>;
}
