import { useState, type FormEvent } from "react";
import type { KnowledgeArea, Project, RoadmapActivity, RoadmapActivityStatus, RoadmapActivityType, RoadmapLearningMethodType, RoadmapResourceType, RoadmapStatus, StudyRoadmap, StudyRoadmapInput } from "../../types";
import { RecordEditorDialog } from "../core/RecordEditorDialog";

const uid = () => crypto.randomUUID();
const learningMethods: RoadmapLearningMethodType[] = ["ACTIVE_RECALL", "FEYNMAN", "SHADOWING", "SPACED_REVIEW", "HANDS_ON", "PROBLEM_SOLVING", "CASE_STUDY", "BUILD", "OBSERVE", "EXPERIMENT", "REFLECTION", "RESEARCH", "OTHER"];
const resourceTypes: RoadmapResourceType[] = ["VIDEO", "ARTICLE", "DOCUMENTATION", "COURSE", "BOOK", "LAB", "TOOL", "PODCAST", "DATASET", "WEBSITE", "OTHER"];
const activity = (order: number): RoadmapActivity => ({ id: uid(), title: "", description: "", activityType: "READING", status: "pending", completedAt: null, order, primaryKnowledgeNodeId: null, secondaryKnowledgeNodeIds: [], projectId: null, researchId: null, learningObjective: null, instructions: null, completionCriteria: null, deliverable: null, estimatedMinutes: null, learningMethod: null, resources: [], isValidation: false, reflectionPrompt: null });
const inputOf = (item?: StudyRoadmap | null): StudyRoadmapInput => item ? { id: item.id, name: item.name, description: item.description, status: item.status, stages: structuredClone(item.stages) } : { id: uid(), name: "", description: "", status: "planned", stages: [] };
type Props = { roadmap?: StudyRoadmap | null; knowledge: KnowledgeArea[]; projects: Project[]; onCancel: () => void; onSave: (input: StudyRoadmapInput) => Promise<void> };

export function RoadmapEditor({ roadmap, knowledge, projects, onCancel, onSave }: Props) {
  const [form, setForm] = useState(() => inputOf(roadmap));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const changeStage = (si: number, fn: (stage: StudyRoadmapInput["stages"][number]) => StudyRoadmapInput["stages"][number]) => setForm((current) => ({ ...current, stages: current.stages.map((stage, index) => index === si ? fn(stage) : stage) }));
  const changeActivity = (si: number, ti: number, ai: number, fn: (entry: RoadmapActivity) => RoadmapActivity) => changeStage(si, (stage) => ({ ...stage, topics: stage.topics.map((topic, index) => index === ti ? { ...topic, activities: topic.activities.map((entry, position) => position === ai ? fn(entry) : entry) } : topic) }));
  const allTopics = form.stages.flatMap((stage) => stage.topics);
  const removeTopic = (topicId: string) => setForm((current) => ({ ...current, stages: current.stages.map((stage) => ({ ...stage, topics: stage.topics.filter((topic) => topic.id !== topicId).map((topic, index) => ({ ...topic, order: index + 1, prerequisiteTopicIds: (topic.prerequisiteTopicIds ?? []).filter((id) => id !== topicId) })) })) }));
  const removeStage = (stageIndex: number) => setForm((current) => { const removedIds = new Set(current.stages[stageIndex]?.topics.map((topic) => topic.id) ?? []); return { ...current, stages: current.stages.filter((_, index) => index !== stageIndex).map((stage, index) => ({ ...stage, order: index + 1, topics: stage.topics.map((topic) => ({ ...topic, prerequisiteTopicIds: (topic.prerequisiteTopicIds ?? []).filter((id) => !removedIds.has(id)) })) })) }; });
  async function submit(event: FormEvent) { event.preventDefault(); setError(null); setBusy(true); try { await onSave(form); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); setBusy(false); } }

  return <RecordEditorDialog eyebrow="STUDY LAB // ROADMAP" title={roadmap ? `Editar ${roadmap.name}` : "Novo roadmap"} busy={busy} error={error} onCancel={onCancel} onSubmit={submit}>
    <label>Nome<input required maxLength={120} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label>
    <label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as RoadmapStatus })}><option value="planned">Planejado</option><option value="active">Ativo</option><option value="paused">Pausado</option><option value="completed">Concluído</option></select></label>
    <label className="record-editor__wide">Descrição<textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label>
    <div className="record-editor__wide roadmap-builder"><header><strong>ETAPAS, TÓPICOS E ATIVIDADES</strong><button type="button" onClick={() => setForm((current) => ({ ...current, stages: [...current.stages, { id: uid(), name: "Nova etapa", description: "", order: current.stages.length + 1, topics: [] }] }))}>＋ ETAPA</button></header>
      {form.stages.map((stage, si) => <section className="roadmap-stage-editor" key={stage.id}>
        <div className="roadmap-builder__line"><b>ETAPA {si + 1}</b><input value={stage.name} onChange={(event) => changeStage(si, (item) => ({ ...item, name: event.target.value }))} /><button type="button" className="danger-link" onClick={() => removeStage(si)}>×</button></div>
        {stage.topics.map((topic, ti) => <article className="roadmap-topic-editor" key={topic.id}>
          <div className="roadmap-builder__line"><span>TÓPICO {ti + 1}</span><input value={topic.name} onChange={(event) => changeStage(si, (item) => ({ ...item, topics: item.topics.map((entry, index) => index === ti ? { ...entry, name: event.target.value } : entry) }))} /><button type="button" onClick={() => removeTopic(topic.id)}>×</button></div>
          <div className="roadmap-builder__fields"><label>Área vinculada<select value={topic.knowledgeNodeId ?? ""} onChange={(event) => changeStage(si, (item) => ({ ...item, topics: item.topics.map((entry, index) => index === ti ? { ...entry, knowledgeNodeId: event.target.value || null } : entry) }))}><option value="">Selecione</option>{knowledge.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label><label className="roadmap-prerequisites">Pré-requisitos<select multiple value={topic.prerequisiteTopicIds ?? []} onChange={(event) => changeStage(si, (item) => ({ ...item, topics: item.topics.map((entry, index) => index === ti ? { ...entry, prerequisiteTopicIds: [...event.target.selectedOptions].map((option) => option.value) } : entry) }))}>{allTopics.filter((item) => item.id !== topic.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><small>Use Ctrl para selecionar mais de um tópico.</small></label></div>
          {topic.activities.map((entry, ai) => <div className="roadmap-activity-editor learning-activity" key={entry.id}>
            <input placeholder="Atividade" value={entry.title} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, title: event.target.value }))} />
            <select value={entry.activityType} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, activityType: event.target.value as RoadmapActivityType }))}>{["READING", "LESSON", "QUIZ", "EXERCISE", "SIMULATION", "EXPERIMENT", "PROJECT", "DOCUMENTATION", "RESEARCH", "OTHER"].map((type) => <option key={type}>{type}</option>)}</select>
            <select value={entry.status} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, status: event.target.value as RoadmapActivityStatus, completedAt: event.target.value === "completed" ? item.completedAt ?? new Date().toISOString() : null }))}><option value="pending">Pendente</option><option value="in_progress">Em andamento</option><option value="completed">Concluída</option></select>
            <button type="button" onClick={() => changeStage(si, (item) => ({ ...item, topics: item.topics.map((current, index) => index === ti ? { ...current, activities: current.activities.filter((_, position) => position !== ai).map((activityItem, position) => ({ ...activityItem, order: position + 1 })) } : current) }))}>×</button>
            <div className="learning-activity__relations">
              <label>Área principal<select value={entry.primaryKnowledgeNodeId ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, primaryKnowledgeNodeId: event.target.value || null }))}><option value="">Usar o tópico</option>{knowledge.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label>
              <label>Secundários<select multiple value={entry.secondaryKnowledgeNodeIds ?? []} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, secondaryKnowledgeNodeIds: [...event.target.selectedOptions].map((option) => option.value) }))}>{knowledge.filter((area) => area.id !== (entry.primaryKnowledgeNodeId ?? topic.knowledgeNodeId)).map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</select></label>
              <label>Projeto<select value={entry.projectId ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, projectId: event.target.value || null }))}><option value="">Sem projeto</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label>
            </div>
            <details className="learning-activity__model">
              <summary>MODELO DE APRENDIZAGEM (OPCIONAL)</summary>
              <div className="learning-activity__model-grid">
                <label>Objetivo<textarea rows={2} value={entry.learningObjective ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, learningObjective: event.target.value || null }))} /></label>
                <label>Instruções<textarea rows={3} value={entry.instructions ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, instructions: event.target.value || null }))} /></label>
                <label>Entrega<textarea rows={2} value={entry.deliverable ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, deliverable: event.target.value || null }))} /></label>
                <label>Critério de conclusão<textarea rows={2} value={entry.completionCriteria ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, completionCriteria: event.target.value || null }))} /></label>
                <label>Reflexão<textarea rows={2} value={entry.reflectionPrompt ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, reflectionPrompt: event.target.value || null }))} /></label>
                <label>Estimativa (min)<input type="number" min={1} max={1440} value={entry.estimatedMinutes ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, estimatedMinutes: event.target.value ? Number(event.target.value) : null }))} /></label>
                <label>Método<select value={entry.learningMethod?.type ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, learningMethod: event.target.value ? { type: event.target.value as RoadmapLearningMethodType, instructions: item.learningMethod?.instructions ?? null } : null }))}><option value="">Sem método</option>{learningMethods.map((method) => <option key={method}>{method}</option>)}</select></label>
                <label>Orientação do método<textarea rows={2} value={entry.learningMethod?.instructions ?? ""} disabled={!entry.learningMethod} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, learningMethod: item.learningMethod ? { ...item.learningMethod, instructions: event.target.value || null } : null }))} /></label>
                <label className="learning-activity__checkpoint"><input type="checkbox" checked={entry.isValidation ?? false} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, isValidation: event.target.checked }))} /> CHECKPOINT DE VALIDAÇÃO</label>
              </div>
              <section className="learning-resource-editor"><header><strong>RECURSOS</strong><button type="button" onClick={() => changeActivity(si, ti, ai, (item) => ({ ...item, resources: [...(item.resources ?? []), { id: uid(), type: "WEBSITE", title: "", url: null, provider: null, language: null, required: false, studyMaterialId: null }] }))}>＋ RECURSO</button></header>
                {(entry.resources ?? []).map((resource, resourceIndex) => <div className="learning-resource-editor__row" key={resource.id}>
                  <select value={resource.type} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, resources: (item.resources ?? []).map((value, index) => index === resourceIndex ? { ...value, type: event.target.value as RoadmapResourceType } : value) }))}>{resourceTypes.map((type) => <option key={type}>{type}</option>)}</select>
                  <input placeholder="Título" value={resource.title} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, resources: (item.resources ?? []).map((value, index) => index === resourceIndex ? { ...value, title: event.target.value } : value) }))} />
                  <input placeholder="https://..." value={resource.url ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, resources: (item.resources ?? []).map((value, index) => index === resourceIndex ? { ...value, url: event.target.value || null } : value) }))} />
                  <input placeholder="Provedor" value={resource.provider ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, resources: (item.resources ?? []).map((value, index) => index === resourceIndex ? { ...value, provider: event.target.value || null } : value) }))} />
                  <input placeholder="pt-BR" value={resource.language ?? ""} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, resources: (item.resources ?? []).map((value, index) => index === resourceIndex ? { ...value, language: event.target.value || null } : value) }))} />
                  <label><input type="checkbox" checked={resource.required} onChange={(event) => changeActivity(si, ti, ai, (item) => ({ ...item, resources: (item.resources ?? []).map((value, index) => index === resourceIndex ? { ...value, required: event.target.checked } : value) }))} /> obrigatório</label>
                  <button type="button" aria-label="Remover recurso" onClick={() => changeActivity(si, ti, ai, (item) => ({ ...item, resources: (item.resources ?? []).filter((_, index) => index !== resourceIndex) }))}>×</button>
                </div>)}
              </section>
            </details>
          </div>)}
          <button type="button" onClick={() => changeStage(si, (stageItem) => ({ ...stageItem, topics: stageItem.topics.map((current, index) => index === ti ? { ...current, activities: [...current.activities, activity(current.activities.length + 1)] } : current) }))}>＋ ATIVIDADE</button>
        </article>)}
        <button type="button" onClick={() => changeStage(si, (item) => ({ ...item, topics: [...item.topics, { id: uid(), name: "Novo tópico", description: "", knowledgeNodeId: null, state: "NOT_STARTED", order: item.topics.length + 1, prerequisiteTopicIds: [], activities: [] }] }))}>＋ TÓPICO</button>
      </section>)}
    </div>
  </RecordEditorDialog>;
}
