import { useEffect, useMemo, useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { marketLabRepository } from "../repositories/marketLabRepository";
import type { MarketAgentDefinition, MarketDataset, MarketDecisionLog, MarketExperimentResult, MarketExperimentSummary, MarketRiskProfile } from "../types";

const money = (value: number, currency = "BRL") => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value);
const pct = (value: number) => `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
const colors = ["#21dff3", "#55f0a7", "#ffbd4a", "#b58cff", "#ff6f91"];

function EquityChart({ result }: { result: MarketExperimentResult }) {
  const series = useMemo(() => result.metrics.map((metric) => ({ metric, points: result.equity.filter((point) => point.agentId === metric.agentId) })), [result]);
  const values = series.flatMap((entry) => entry.points.map((point) => point.equity));
  const min = Math.min(...values); const max = Math.max(...values); const range = Math.max(max - min, 1);
  return <div className="market-chart"><svg viewBox="0 0 900 250" preserveAspectRatio="none" role="img" aria-label="Curvas patrimoniais dos agentes">
    {[0, 1, 2, 3, 4].map((line) => <line key={line} x1="0" x2="900" y1={line * 62.5} y2={line * 62.5} />)}
    {series.map((entry, seriesIndex) => { const denominator = Math.max(entry.points.length - 1, 1); const points = entry.points.map((point, index) => `${index / denominator * 900},${235 - (point.equity - min) / range * 220}`).join(" "); return <polyline key={entry.metric.agentId} points={points} style={{ stroke: colors[seriesIndex % colors.length] }} />; })}
  </svg><div className="market-chart__legend">{series.map((entry, index) => <span key={entry.metric.agentId}><i style={{ background: colors[index % colors.length] }} />{entry.metric.agentName}</span>)}</div></div>;
}

export function MarketLabPage() {
  const [datasets, setDatasets] = useState<MarketDataset[]>([]); const [agents, setAgents] = useState<MarketAgentDefinition[]>([]); const [profiles, setProfiles] = useState<MarketRiskProfile[]>([]); const [history, setHistory] = useState<MarketExperimentSummary[]>([]);
  const [result, setResult] = useState<MarketExperimentResult | null>(null); const [selectedAgents, setSelectedAgents] = useState<string[]>(["cash", "buy-hold", "simple-trend"]); const [tab, setTab] = useState<"overview" | "decisions" | "history">("overview");
  const [name, setName] = useState("Experimento determinístico"); const [datasetId, setDatasetId] = useState(""); const [profileId, setProfileId] = useState(""); const [capital, setCapital] = useState(10_000); const [seed, setSeed] = useState(42); const [fee, setFee] = useState(0.1); const [slippage, setSlippage] = useState(0.05);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [logAgent, setLogAgent] = useState("all"); const [logAction, setLogAction] = useState("all");

  const load = async () => { const [nextDatasets, nextAgents, nextProfiles, nextHistory] = await Promise.all([marketLabRepository.listDatasets(), marketLabRepository.listAgents(), marketLabRepository.listRiskProfiles(), marketLabRepository.listExperiments()]); setDatasets(nextDatasets); setAgents(nextAgents); setProfiles(nextProfiles); setHistory(nextHistory); setDatasetId((current) => current || nextDatasets[0]?.id || ""); setProfileId((current) => current || nextProfiles[0]?.id || ""); };
  useEffect(() => {
    void Promise.all([marketLabRepository.listDatasets(), marketLabRepository.listAgents(), marketLabRepository.listRiskProfiles(), marketLabRepository.listExperiments()]).then(([nextDatasets, nextAgents, nextProfiles, nextHistory]) => {
      setDatasets(nextDatasets); setAgents(nextAgents); setProfiles(nextProfiles); setHistory(nextHistory); setDatasetId(nextDatasets[0]?.id || ""); setProfileId(nextProfiles[0]?.id || "");
    }).catch((cause) => setError(String(cause)));
  }, []);

  const importCsv = async () => { const path = await open({ multiple: false, filters: [{ name: "Historical candles", extensions: ["csv"] }] }); if (!path) return; const basename = path.split(/[\\/]/).pop()?.replace(/\.csv$/i, "") || "Dataset"; const asset = window.prompt("Código do ativo", "TEST")?.trim(); if (!asset) return; const timeframe = window.prompt("Timeframe", "1D")?.trim(); if (!timeframe) return; setBusy(true); setError(null); try { const dataset = await marketLabRepository.importDataset({ path, name: basename, asset, timeframe, currency: "BRL" }); await load(); setDatasetId(dataset.id); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const run = async () => { if (!datasetId || !profileId) { setError("Importe um dataset e selecione o perfil de risco."); return; } setBusy(true); setError(null); try { const next = await marketLabRepository.runExperiment({ name, datasetId, riskProfileId: profileId, agentIds: selectedAgents, initialCapital: capital, randomSeed: seed, feePct: fee, slippagePct: slippage }); setResult(next); setTab("overview"); await load(); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const openExperiment = async (id: string) => { setBusy(true); setError(null); try { setResult(await marketLabRepository.getExperiment(id)); setTab("overview"); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const rerun = async () => { if (!result) return; setBusy(true); setError(null); try { setResult(await marketLabRepository.rerunExperiment(result.experiment.id)); await load(); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const toggleAgent = (id: string) => setSelectedAgents((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 5 ? [...current, id] : current);
  const filteredLogs = useMemo(() => (result?.decisions ?? []).filter((log) => (logAgent === "all" || log.agentId === logAgent) && (logAction === "all" || log.action === logAction)), [result, logAgent, logAction]);

  return <section className="market-lab">
    <header className="module-header market-lab__header"><div><span className="eyebrow">LAB / MARKET LAB v0.1</span><h1>Deterministic Backtest Core</h1><p>Laboratório quantitativo local. Simulação histórica, sem corretora, sem dinheiro real e sem decisões por IA.</p></div><div className="market-header-actions"><button className="button market-kill" onClick={() => void marketLabRepository.activateKillSwitch()}>KILL SWITCH</button><button className="button button--primary" onClick={() => void importCsv()} disabled={busy}>+ IMPORTAR CSV</button></div></header>
    {error && <div className="market-alert"><strong>OPERAÇÃO INTERROMPIDA</strong><span>{error}</span><button onClick={() => setError(null)}>×</button></div>}
    <div className="market-lab__grid">
      <aside className="hud-panel market-config"><div className="panel-heading"><strong>NOVO EXPERIMENTO</strong><span>MAX 5 AGENTES</span></div>
        <label>NOME<input value={name} onChange={(event) => setName(event.target.value)} /></label>
        <label>DATASET<select value={datasetId} onChange={(event) => setDatasetId(event.target.value)}><option value="">Nenhum dataset</option>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.asset} / {dataset.timeframe} · {dataset.candleCount}</option>)}</select></label>
        {datasets.find((item) => item.id === datasetId) && <div className="market-dataset-card"><strong>{datasets.find((item) => item.id === datasetId)?.name}</strong><span>{datasets.find((item) => item.id === datasetId)?.startAt} → {datasets.find((item) => item.id === datasetId)?.endAt}</span><small>{datasets.find((item) => item.id === datasetId)?.fingerprint}</small></div>}
        <label>RISK PROFILE<select value={profileId} onChange={(event) => setProfileId(event.target.value)}>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name} · max {profile.maxPositionPct}%</option>)}</select></label>
        <div className="market-form-row"><label>CAPITAL / AGENTE<input type="number" min="1" value={capital} onChange={(event) => setCapital(Number(event.target.value))} /></label><label>SEED<input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} /></label></div>
        <div className="market-form-row"><label>FEE %<input type="number" step="0.01" min="0" value={fee} onChange={(event) => setFee(Number(event.target.value))} /></label><label>SLIPPAGE %<input type="number" step="0.01" min="0" value={slippage} onChange={(event) => setSlippage(Number(event.target.value))} /></label></div>
        <fieldset><legend>AGENT REGISTRY · {selectedAgents.length}/5</legend>{agents.map((agent) => <label className="market-agent-check" key={agent.id}><input type="checkbox" checked={selectedAgents.includes(agent.id)} onChange={() => toggleAgent(agent.id)} disabled={!agent.enabled || (!selectedAgents.includes(agent.id) && selectedAgents.length >= 5)} /><span><strong>{agent.name}</strong><small>{agent.strategyType} / {agent.strategyVersion}</small></span></label>)}</fieldset>
        <button className="button button--primary market-run" onClick={() => void run()} disabled={busy || selectedAgents.length === 0}>{busy ? "RUNNING..." : "▶ RUN BACKTEST"}</button>
      </aside>
      <main className="hud-panel market-results"><div className="market-tabs"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>VISÃO GERAL</button><button className={tab === "decisions" ? "active" : ""} onClick={() => setTab("decisions")}>DECISION / RISK / EXECUTION</button><button className={tab === "history" ? "active" : ""} onClick={() => setTab("history")}>HISTÓRICO ({history.length})</button></div>
        {!result && tab !== "history" && <div className="market-empty"><span>◇</span><strong>NENHUM EXPERIMENTO SELECIONADO</strong><p>Importe candles OHLCV locais, selecione agentes e execute um backtest.</p></div>}
        {result && tab === "overview" && <><div className="market-result-head"><div><span>EXPERIMENTO / {result.experiment.status.toUpperCase()}</span><h2>{result.experiment.name}</h2><p>{result.experiment.asset} · {result.experiment.timeframe} · {result.experiment.datasetName}</p></div><button className="button" onClick={() => void rerun()} disabled={busy}>CLONAR / EXECUTAR NOVAMENTE</button></div><div className="market-metrics"><table><thead><tr><th>AGENTE</th><th>EQUITY FINAL</th><th>RETORNO</th><th>DRAWDOWN</th><th>TRADES</th><th>HOLD</th><th>EXPOSIÇÃO</th></tr></thead><tbody>{result.metrics.map((metric) => <tr key={metric.agentId}><td><strong>{metric.agentName}</strong><small>{metric.status}</small></td><td>{money(metric.finalEquity, result.experiment.currency)}</td><td className={metric.totalReturnPct >= 0 ? "positive" : "negative"}>{pct(metric.totalReturnPct)}</td><td>{metric.maxDrawdownPct.toFixed(2)}%</td><td>{metric.tradeCount}</td><td>{metric.holdCount}</td><td>{metric.averageExposurePct.toFixed(1)}% / {metric.maxExposurePct.toFixed(1)}%</td></tr>)}</tbody></table></div><div className="panel-heading"><strong>EQUITY CURVE</strong><span>MARK-TO-MARKET / SEM LIQUIDAÇÃO FORÇADA</span></div><EquityChart result={result} /></>}
        {result && tab === "decisions" && <LogView logs={filteredLogs} agent={logAgent} action={logAction} setAgent={setLogAgent} setAction={setLogAction} agents={result.metrics.map((metric) => ({ id: metric.agentId, name: metric.agentName }))} />}
        {tab === "history" && <div className="market-history">{history.length === 0 ? <div className="market-empty"><strong>HISTÓRICO VAZIO</strong></div> : history.map((experiment) => <button key={experiment.id} onClick={() => void openExperiment(experiment.id)}><div><strong>{experiment.name}</strong><span>{experiment.datasetName} · {experiment.asset} / {experiment.timeframe}</span></div><div><strong>{experiment.status.toUpperCase()}</strong><span>{experiment.agentIds.length} agentes · seed {experiment.randomSeed}</span></div></button>)}</div>}
      </main>
    </div>
  </section>;
}

function LogView({ logs, agent, action, setAgent, setAction, agents }: { logs: MarketDecisionLog[]; agent: string; action: string; setAgent: (value: string) => void; setAction: (value: string) => void; agents: Array<{ id: string; name: string }> }) {
  return <div className="market-log"><div className="market-log__filters"><label>AGENTE<select value={agent} onChange={(event) => setAgent(event.target.value)}><option value="all">Todos</option>{agents.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>AÇÃO<select value={action} onChange={(event) => setAction(event.target.value)}><option value="all">Todas</option><option>BUY</option><option>SELL</option><option>HOLD</option></select></label><span>{logs.length} REGISTROS</span></div><div className="market-log__rows">{logs.map((log) => <article key={log.id}><header><strong>{log.action}</strong><span>{log.agentId}</span><time>{log.timestamp}</time><i className={log.riskResult.toLowerCase()}>{log.riskResult}</i></header><p>{log.reasoning}</p><dl><div><dt>OBSERVADO</dt><dd>{log.observedPrice.toFixed(6)}</dd></div><div><dt>RISCO</dt><dd>{log.riskReason}</dd></div><div><dt>EXECUÇÃO T+1</dt><dd>{log.executionPrice == null ? "SEM ORDEM" : `${log.executionPrice.toFixed(6)} · QTD ${log.quantity?.toFixed(6)} · FEE ${log.fees?.toFixed(6)}`}</dd></div></dl></article>)}</div></div>;
}
