import { useEffect, useMemo, useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { MarketObservatory } from "../components/market/MarketObservatory";
import { MarketValidation } from "../components/market/MarketValidation";
import { AiAbcComparisonPanel, AiRuntimePanel, SignalDiagnosticsPanel } from "../components/market/MarketAiDiagnostics";
import { MarketIntradayPanel } from "../components/market/MarketIntradayPanel";
import { downsampleEquity } from "../components/market/marketIntraday";
import { marketLabRepository } from "../repositories/marketLabRepository";
import type { MarketAgentDefinition, MarketAiDecisionLog, MarketAiExperimentComparison, MarketAiRuntimeMetric, MarketAiStatus, MarketDataset, MarketExperimentResult, MarketExperimentSummary, MarketRiskProfile, MarketSignalDiagnostics } from "../types";

const money = (value: number, currency = "BRL") => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value);
const pct = (value: number) => `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;
const colors = ["#21dff3", "#55f0a7", "#ffbd4a", "#b58cff", "#ff6f91"];

function EquityChart({ result }: { result: MarketExperimentResult }) {
  const series = useMemo(() => result.metrics.map((metric) => ({ metric, points: downsampleEquity(result.equity.filter((point) => point.agentId === metric.agentId)) })), [result]);
  const values = series.flatMap((entry) => entry.points.map((point) => point.equity));
  const min = Math.min(...values); const max = Math.max(...values); const range = Math.max(max - min, 1);
  return <div className="market-chart"><svg viewBox="0 0 900 250" preserveAspectRatio="none" role="img" aria-label="Curvas patrimoniais dos agentes">
    {[0, 1, 2, 3, 4].map((line) => <line key={line} x1="0" x2="900" y1={line * 62.5} y2={line * 62.5} />)}
    {series.map((entry, seriesIndex) => { const denominator = Math.max(entry.points.length - 1, 1); const points = entry.points.map((point, index) => `${index / denominator * 900},${235 - (point.equity - min) / range * 220}`).join(" "); return <polyline key={entry.metric.agentId} points={points} style={{ stroke: colors[seriesIndex % colors.length] }} />; })}
  </svg><div className="market-chart__legend">{series.map((entry, index) => <span key={entry.metric.agentId}><i style={{ background: colors[index % colors.length] }} />{entry.metric.agentName}</span>)}</div></div>;
}

export function MarketLabPage() {
  const [datasets, setDatasets] = useState<MarketDataset[]>([]); const [agents, setAgents] = useState<MarketAgentDefinition[]>([]); const [profiles, setProfiles] = useState<MarketRiskProfile[]>([]); const [history, setHistory] = useState<MarketExperimentSummary[]>([]);
  const [result, setResult] = useState<MarketExperimentResult | null>(null); const [selectedAgents, setSelectedAgents] = useState<string[]>(["cash", "buy-hold", "simple-trend"]); const [tab, setTab] = useState<"overview" | "experiments" | "agents" | "observatory" | "validation" | "datasets">("overview");
  const [name, setName] = useState("Experimento determinístico"); const [datasetId, setDatasetId] = useState(""); const [profileId, setProfileId] = useState(""); const [capital, setCapital] = useState(10_000); const [seed, setSeed] = useState(42); const [fee, setFee] = useState(0.1); const [slippage, setSlippage] = useState(0.05);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const [aiStatus, setAiStatus] = useState<MarketAiStatus | null>(null); const [aiRuntime, setAiRuntime] = useState<MarketAiRuntimeMetric | null>(null); const [aiDecisions, setAiDecisions] = useState<MarketAiDecisionLog[]>([]); const [aiInterval, setAiInterval] = useState(5); const [aiTimeoutMs, setAiTimeoutMs] = useState(30000); const [aiRetries, setAiRetries] = useState(1);
  const [aiComparisons, setAiComparisons] = useState<MarketAiExperimentComparison[]>([]);
  const [signalDiagnostics, setSignalDiagnostics] = useState<MarketSignalDiagnostics | null>(null);

  const selectedAiAgentId = selectedAgents.find((id) => id.startsWith("ai-technical-"));
  const selectedDataset = datasets.find((item) => item.id === datasetId);
  const chooseDataset = (nextDatasetId: string) => {
    setDatasetId(nextDatasetId);
    if (datasets.find((item) => item.id === nextDatasetId)?.timeframe !== "15M") {
      setSelectedAgents((current) => current.filter((id) => !id.startsWith("intraday-")));
    }
  };
  const applyAiStatus = (nextAiStatus: MarketAiStatus) => { setAiStatus(nextAiStatus); setAiInterval(nextAiStatus.decisionInterval); setAiTimeoutMs(nextAiStatus.timeoutMs); setAiRetries(nextAiStatus.maxRetries); };
  const load = async () => { const [nextDatasets, nextAgents, nextProfiles, nextHistory, nextAiStatus, nextComparisons] = await Promise.all([marketLabRepository.listDatasets(), marketLabRepository.listAgents(), marketLabRepository.listRiskProfiles(), marketLabRepository.listExperiments(), marketLabRepository.getAiStatus(selectedAiAgentId), marketLabRepository.listAiExperimentComparisons()]); setDatasets(nextDatasets); setAgents(nextAgents); setProfiles(nextProfiles); setHistory(nextHistory); applyAiStatus(nextAiStatus); setAiComparisons(nextComparisons); setDatasetId((current) => current || nextDatasets[0]?.id || ""); setProfileId((current) => current || nextProfiles[0]?.id || ""); };
  useEffect(() => {
    void Promise.all([marketLabRepository.listDatasets(), marketLabRepository.listAgents(), marketLabRepository.listRiskProfiles(), marketLabRepository.listExperiments(), marketLabRepository.getAiStatus(), marketLabRepository.listAiExperimentComparisons()]).then(([nextDatasets, nextAgents, nextProfiles, nextHistory, nextAiStatus, nextComparisons]) => {
      setDatasets(nextDatasets); setAgents(nextAgents); setProfiles(nextProfiles); setHistory(nextHistory); applyAiStatus(nextAiStatus); setAiComparisons(nextComparisons); setDatasetId(nextDatasets[0]?.id || ""); setProfileId(nextProfiles[0]?.id || "");
    }).catch((cause) => setError(String(cause)));
  }, []);

  const importCsv = async () => { const path = await open({ multiple: false, filters: [{ name: "Historical candles", extensions: ["csv"] }] }); if (!path) return; const basename = path.split(/[\\/]/).pop()?.replace(/\.csv$/i, "") || "Dataset"; const asset = window.prompt("Código do ativo", "AAPL")?.trim(); if (!asset) return; const selectedTimeframe = window.prompt("Timeframe suportado: 1D ou 15M", "15M")?.trim().toUpperCase(); if (selectedTimeframe !== "1D" && selectedTimeframe !== "15M") { setError("Timeframe inválido. A v0.5 aceita somente 1D ou 15M."); return; } const intraday = selectedTimeframe === "15M"; setBusy(true); setError(null); try { const dataset = await marketLabRepository.importDataset({ path, name: basename, asset, timeframe: selectedTimeframe, currency: intraday ? "USD" : "BRL", market: intraday ? "US_EQUITIES" : "UNSPECIFIED", timezone: intraday ? "America/New_York" : "UTC", sessionType: intraday ? "REGULAR" : "DAILY" }); await load(); setDatasetId(dataset.id); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const run = async () => { if (!datasetId || !profileId) { setError("Importe um dataset e selecione o perfil de risco."); return; } setBusy(true); setError(null); try { if (selectedAiAgentId) await marketLabRepository.updateAiConfig({ agentId: selectedAiAgentId, decisionInterval: aiInterval, timeoutMs: aiTimeoutMs, maxRetries: aiRetries }); const next = await marketLabRepository.runExperiment({ name, datasetId, riskProfileId: profileId, agentIds: selectedAgents, initialCapital: capital, randomSeed: seed, feePct: fee, slippagePct: slippage }); const [runtime, decisions, diagnostics] = await Promise.all([marketLabRepository.listAiRuntime(next.experiment.id), marketLabRepository.listAiDecisions(next.experiment.id), marketLabRepository.getSignalDiagnostics(next.experiment.id)]); setAiRuntime(runtime[0] ?? null); setAiDecisions(decisions); setSignalDiagnostics(diagnostics); setResult(next); setTab("overview"); await load(); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const openExperiment = async (id: string) => { setBusy(true); setError(null); try { const [next, runtime, decisions, diagnostics] = await Promise.all([marketLabRepository.getExperiment(id), marketLabRepository.listAiRuntime(id), marketLabRepository.listAiDecisions(id), marketLabRepository.getSignalDiagnostics(id)]); setResult(next); setAiRuntime(runtime[0] ?? null); setAiDecisions(decisions); setSignalDiagnostics(diagnostics); setTab("overview"); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const rerun = async () => { if (!result) return; setBusy(true); setError(null); try { const next=await marketLabRepository.rerunExperiment(result.experiment.id); const [runtime,decisions,diagnostics]=await Promise.all([marketLabRepository.listAiRuntime(next.experiment.id),marketLabRepository.listAiDecisions(next.experiment.id),marketLabRepository.getSignalDiagnostics(next.experiment.id)]); setResult(next); setAiRuntime(runtime[0]??null); setAiDecisions(decisions);setSignalDiagnostics(diagnostics); await load(); } catch (cause) { setError(String(cause)); } finally { setBusy(false); } };
  const toggleAgent = (id: string) => { setSelectedAgents((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 5 ? [...current, id] : current); if (id.startsWith("ai-technical-") && !selectedAgents.includes(id)) void marketLabRepository.getAiStatus(id).then(applyAiStatus).catch((cause) => setError(String(cause))); };

  return <section className="market-lab">
      <header className="module-header market-lab__header"><div><span className="eyebrow">LAB / MARKET LAB v0.5.1</span><h1>Intraday Strategy Lab</h1><p>Feature Engine auditável, três estilos determinísticos e o mesmo pipeline de risco e execução.</p></div><div className="market-header-actions"><button className="button market-kill" onClick={() => void marketLabRepository.activateKillSwitch()}>KILL SWITCH</button><button className="button button--primary" onClick={() => void importCsv()} disabled={busy}>+ IMPORTAR CSV</button></div></header>
    {error && <div className="market-alert"><strong>OPERAÇÃO INTERROMPIDA</strong><span>{error}</span><button onClick={() => setError(null)}>×</button></div>}
    <div className="market-lab__grid">
      <aside className="hud-panel market-config"><div className="panel-heading"><strong>NOVO EXPERIMENTO</strong><span>MAX 5 AGENTES</span></div>
        <label>NOME<input value={name} onChange={(event) => setName(event.target.value)} /></label>
        <label>DATASET<select value={datasetId} onChange={(event) => chooseDataset(event.target.value)}><option value="">Nenhum dataset</option>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.asset} / {dataset.timeframe} · {dataset.candleCount}</option>)}</select></label>
        {datasets.find((item) => item.id === datasetId) && <div className="market-dataset-card"><strong>{datasets.find((item) => item.id === datasetId)?.name}</strong><span>{datasets.find((item) => item.id === datasetId)?.startAt} → {datasets.find((item) => item.id === datasetId)?.endAt}</span><small>{datasets.find((item) => item.id === datasetId)?.market} · {datasets.find((item) => item.id === datasetId)?.sessionType} · {datasets.find((item) => item.id === datasetId)?.timezone}</small></div>}
        <label>RISK PROFILE<select value={profileId} onChange={(event) => setProfileId(event.target.value)}>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name} · max {profile.maxPositionPct}%</option>)}</select></label>
        <div className="market-form-row"><label>CAPITAL / AGENTE<input type="number" min="1" value={capital} onChange={(event) => setCapital(Number(event.target.value))} /></label><label>SEED<input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} /></label></div>
        <div className="market-form-row"><label>FEE %<input type="number" step="0.01" min="0" value={fee} onChange={(event) => setFee(Number(event.target.value))} /></label><label>SLIPPAGE %<input type="number" step="0.01" min="0" value={slippage} onChange={(event) => setSlippage(Number(event.target.value))} /></label></div>
        <fieldset><legend>AGENT REGISTRY · {selectedAgents.length}/5</legend>{agents.map((agent) => { const anotherAiSelected = agent.strategyType === "llm" && Boolean(selectedAiAgentId) && selectedAiAgentId !== agent.id; const intradayUnavailable = agent.id.startsWith("intraday-") && selectedDataset?.timeframe !== "15M"; return <label className={`market-agent-check${intradayUnavailable ? " unavailable" : ""}`} key={agent.id}><input type="checkbox" checked={selectedAgents.includes(agent.id)} onChange={() => toggleAgent(agent.id)} disabled={!agent.enabled || anotherAiSelected || intradayUnavailable || (!selectedAgents.includes(agent.id) && selectedAgents.length >= 5)} /><span><strong>{agent.name}{agent.strategyType === "llm" && <b className="market-ai-badge">AI</b>}{agent.id.startsWith("intraday-") && <b className="market-timeframe-badge">15M</b>}</strong><small>{agent.strategyType} / {agent.strategyVersion}{agent.strategyType === "llm" && ` · ${aiStatus?.model ?? "MODEL"}`}{intradayUnavailable && " · selecione dataset 15M"}</small></span></label>; })}</fieldset>
        {selectedAiAgentId && <section className="market-ai-config"><div className="panel-heading"><strong>AI AGENT</strong><span className={aiStatus?.available ? "online" : "offline"}>{aiStatus?.available ? "ONLINE" : "DEGRADED"}</span></div><label>DECISION INTERVAL<select value={aiInterval} onChange={(event)=>setAiInterval(Number(event.target.value))}><option value={1}>1 candle</option><option value={5}>5 candles</option><option value={10}>10 candles</option></select></label><div className="market-form-row"><label>TIMEOUT MS<input type="number" min="5000" max="180000" step="1000" value={aiTimeoutMs} onChange={(event)=>setAiTimeoutMs(Number(event.target.value))}/></label><label>MAX RETRIES<select value={aiRetries} onChange={(event)=>setAiRetries(Number(event.target.value))}><option value={0}>0</option><option value={1}>1</option></select></label></div><small>{aiStatus?.provider.toUpperCase()} / {aiStatus?.model} / {aiStatus?.promptVersion}</small>{!aiStatus?.available&&<p>O provider está offline. O agente continuará em fallback HOLD sem interromper a coorte.</p>}</section>}
        <button className="button button--primary market-run" onClick={() => void run()} disabled={busy || selectedAgents.length < 3}>{busy ? "RUNNING..." : "▶ RUN COHORT"}</button>
        {selectedAgents.length < 3 && <small className="market-config__hint">Selecione pelo menos 3 agentes para formar uma coorte.</small>}
      </aside>
      <main className={`hud-panel market-results${result && tab === "overview" ? " market-results--overview" : ""}`}><div className="market-tabs market-tabs--v3"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>OVERVIEW</button><button className={tab === "experiments" ? "active" : ""} onClick={() => setTab("experiments")}>EXPERIMENTS</button><button className={tab === "agents" ? "active" : ""} onClick={() => setTab("agents")}>AGENTS</button><button className={tab === "observatory" ? "active" : ""} onClick={() => setTab("observatory")}>OBSERVATORY</button><button className={tab === "validation" ? "active" : ""} onClick={() => setTab("validation")}>VALIDATION</button><button className={tab === "datasets" ? "active" : ""} onClick={() => setTab("datasets")}>DATASETS</button></div>
        {!result && (tab === "overview" || tab === "observatory") && <div className="market-empty"><span>◇</span><strong>NENHUMA COORTE SELECIONADA</strong><p>Importe candles OHLCV locais, selecione de 3 a 5 agentes e execute um experimento.</p></div>}
        {result && tab === "overview" && <div className="market-overview-actions"><button className="button" type="button" onClick={() => window.print()}>EXPORTAR OVERVIEW / PDF</button></div>}
        {result && tab === "overview" && <><div className="market-result-head"><div><span>EXPERIMENTO / {result.experiment.status.toUpperCase()}</span><h2>{result.experiment.name}</h2><p>{result.experiment.asset} · {result.experiment.timeframe} · {result.experiment.datasetName}</p></div><button className="button" onClick={() => void rerun()} disabled={busy}>CLONAR / EXECUTAR NOVAMENTE</button></div><div className="market-metrics"><table><thead><tr><th>AGENTE</th><th>EQUITY FINAL</th><th>RETORNO</th><th>DRAWDOWN</th><th>TRADES</th><th>HOLD</th><th>EXPOSIÇÃO</th></tr></thead><tbody>{result.metrics.map((metric) => <tr key={metric.agentId}><td><strong>{metric.agentName}{metric.agentId.startsWith("ai-technical-")&&<b className="market-ai-badge">AI</b>}</strong><small>{metric.status}</small></td><td>{money(metric.finalEquity, result.experiment.currency)}</td><td className={metric.totalReturnPct >= 0 ? "positive" : "negative"}>{pct(metric.totalReturnPct)}</td><td>{metric.maxDrawdownPct.toFixed(2)}%</td><td>{metric.tradeCount}</td><td>{metric.holdCount}</td><td>{metric.averageExposurePct.toFixed(1)}% / {metric.maxExposurePct.toFixed(1)}%</td></tr>)}</tbody></table></div><div className="panel-heading"><strong>EQUITY CURVE</strong><span>MARK-TO-MARKET / SEM LIQUIDAÇÃO FORÇADA</span></div><EquityChart result={result} /><MarketIntradayPanel result={result}/><AiRuntimePanel status={aiStatus} runtime={aiRuntime} decisions={aiDecisions}/><SignalDiagnosticsPanel diagnostics={signalDiagnostics}/></>}
        {result && tab === "observatory" && <MarketObservatory result={result} aiDecisions={aiDecisions} />}
        {tab === "validation" && <MarketValidation datasets={datasets} agents={agents} profiles={profiles} datasetId={datasetId} riskProfileId={profileId} agentIds={selectedAgents} initialCapital={capital} randomSeed={seed} feePct={fee} slippagePct={slippage} onError={(message) => setError(message)} />}
        {tab === "experiments" && <><AiAbcComparisonPanel entries={aiComparisons}/><div className="market-history">{history.length === 0 ? <div className="market-empty"><strong>HISTÓRICO VAZIO</strong></div> : history.map((experiment) => <button key={experiment.id} onClick={() => void openExperiment(experiment.id)}><div><strong>{experiment.name}</strong><span>{experiment.datasetName} · {experiment.asset} / {experiment.timeframe}</span></div><div><strong>{experiment.status.toUpperCase()}</strong><span>{experiment.agentIds.length} agentes · seed {experiment.randomSeed}</span></div></button>)}</div></>}
        {tab === "agents" && <div className="market-registry-view">{agents.map((agent) => <article key={agent.id}><div><strong>{agent.name}{agent.strategyType === "llm"&&<b className="market-ai-badge">AI</b>}</strong><span>{agent.strategyType} / {agent.strategyVersion}{agent.strategyType === "llm"&&` · ${aiStatus?.model}`}</span></div><b>{agent.strategyType === "llm"?(aiStatus?.available?"ONLINE":"DEGRADED"):(agent.enabled ? "ENABLED" : "DISABLED")}</b><code>{agent.defaultConfigJson}</code></article>)}</div>}
        {tab === "datasets" && <div className="market-registry-view">{datasets.length === 0 ? <div className="market-empty"><strong>NENHUM DATASET</strong></div> : datasets.map((dataset) => <article key={dataset.id}><div><strong>{dataset.name}</strong><span>{dataset.asset} / {dataset.timeframe} · {dataset.candleCount} candles · {dataset.sessionCount} sessões</span></div><b>{dataset.market} · {dataset.sessionType}<small>{dataset.timezone} · gaps esperados {dataset.expectedGapCount} / inesperados {dataset.unexpectedGapCount}</small></b><code>{dataset.fingerprint}</code></article>)}</div>}
      </main>
    </div>
  </section>;
}
