import type { AddLinkStudyMaterialInput, ImportStudyMaterialInput, ImportStudyMaterialResult, MaterialTextContent, StartStudyReviewSessionInput, StartStudySessionInput, StudyCard, StudyCardInput, StudyCardListInput, StudyMaterial, StudyMaterialListInput, StudyMaterialRelation, StudyMaterialRelationInput, StudyMaterialStatus, StudyMaterialSummary, StudyNotebook, StudyNotebookInput, StudyNote, StudyNoteInput, StudyNoteListInput, StudyNoteSearchInput, StudyNoteSummary, StudyReviewDashboardSummary, StudyReviewQueueItem, StudyReviewQueueMode, StudyReviewResult, StudyReviewSession, StudyReviewSessionListInput, StudyReviewSummary, StudySession, StudySessionListInput, StudySettings, StudySettingsInput, StudyTodaySummary, SubmitStudyReviewResultInput, UpdateStudyMaterialInput } from "../types";
import { invokeDatabase } from "./tauri";

export const studyLabRepository = {
  startSession: (input: StartStudySessionInput) => invokeDatabase<StudySession>("start_study_session", { input }),
  pauseSession: (id: string) => invokeDatabase<StudySession>("pause_study_session", { id }),
  resumeSession: (id: string) => invokeDatabase<StudySession>("resume_study_session", { id }),
  completeSession: (id: string) => invokeDatabase<StudySession>("complete_study_session", { id }),
  cancelSession: (id: string) => invokeDatabase<StudySession>("cancel_study_session", { id }),
  activeSession: () => invokeDatabase<StudySession | null>("get_active_study_session"),
  sessions: (input: StudySessionListInput) => invokeDatabase<StudySession[]>("list_study_sessions", { input }),
  todaySummary: () => invokeDatabase<StudyTodaySummary>("get_study_today_summary"),
  settings: () => invokeDatabase<StudySettings>("get_study_settings"),
  updateSettings: (input: StudySettingsInput) => invokeDatabase<StudySettings>("update_study_settings", { input }),
  notebooks: (includeArchived = false) => invokeDatabase<StudyNotebook[]>("list_study_notebooks", { includeArchived }),
  notebook: (id: string) => invokeDatabase<StudyNotebook | null>("get_study_notebook", { id }),
  saveNotebook: (input: StudyNotebookInput) => invokeDatabase<StudyNotebook>("save_study_notebook", { input }),
  archiveNotebook: (id: string) => invokeDatabase<StudyNotebook>("archive_study_notebook", { id }),
  restoreNotebook: (id: string) => invokeDatabase<StudyNotebook>("restore_study_notebook", { id }),
  deleteNotebook: (id: string) => invokeDatabase<void>("delete_study_notebook", { id }),
  note: (id: string) => invokeDatabase<StudyNote | null>("get_study_note", { id }),
  saveNote: (input: StudyNoteInput) => invokeDatabase<StudyNote>("save_study_note", { input }),
  createNoteFromMaterial: (materialId: string, input: StudyNoteInput) => invokeDatabase<StudyNote>("create_study_note_from_material", { materialId, input }),
  deleteNote: (id: string) => invokeDatabase<void>("delete_study_note", { id }),
  notes: (input: StudyNoteListInput) => invokeDatabase<StudyNoteSummary[]>("list_study_notes", { input }),
  searchNotes: (input: StudyNoteSearchInput) => invokeDatabase<StudyNoteSummary[]>("search_study_notes", { input }),
  recentNotes: (limit = 5) => invokeDatabase<StudyNoteSummary[]>("list_recent_study_notes", { limit }),
  saveCard: (input: StudyCardInput) => invokeDatabase<StudyCard>("save_study_card", { input }),
  saveCards: (inputs: StudyCardInput[]) => invokeDatabase<StudyCard[]>("save_study_cards", { inputs }),
  card: (id: string) => invokeDatabase<StudyCard | null>("get_study_card", { id }),
  cards: (input: StudyCardListInput) => invokeDatabase<StudyCard[]>("list_study_cards", { input }),
  setCardStatus: (id: string, status: StudyCard["status"]) => invokeDatabase<StudyCard>("set_study_card_status", { id, status }),
  deleteCard: (id: string) => invokeDatabase<void>("delete_study_card", { id }),
  reviewDashboard: () => invokeDatabase<StudyReviewDashboardSummary>("get_study_review_dashboard_summary"),
  reviewQueue: (mode: StudyReviewQueueMode) => invokeDatabase<StudyReviewQueueItem[]>("get_study_review_queue", { mode }),
  startReviewSession: (input: StartStudyReviewSessionInput) => invokeDatabase<StudyReviewSession>("start_study_review_session", { input }),
  activeReviewSession: () => invokeDatabase<StudyReviewSession | null>("get_active_study_review_session"),
  submitReviewResult: (input: SubmitStudyReviewResultInput) => invokeDatabase<StudyReviewResult>("submit_study_review_result", { input }),
  completeReviewSession: (id: string) => invokeDatabase<StudyReviewSession>("complete_study_review_session", { id }),
  cancelReviewSession: (id: string) => invokeDatabase<StudyReviewSession>("cancel_study_review_session", { id }),
  reviewSummary: (id: string) => invokeDatabase<StudyReviewSummary>("get_study_review_summary", { id }),
  reviewSessions: (input: StudyReviewSessionListInput) => invokeDatabase<StudyReviewSession[]>("list_study_review_sessions", { input }),
  importMaterial: (input: ImportStudyMaterialInput) => invokeDatabase<ImportStudyMaterialResult>("import_study_material", { input }),
  addLinkMaterial: (input: AddLinkStudyMaterialInput) => invokeDatabase<StudyMaterial>("add_study_link_material", { input }),
  materials: (input: StudyMaterialListInput) => invokeDatabase<StudyMaterialSummary[]>("list_study_materials", { input }),
  material: (id: string) => invokeDatabase<StudyMaterial | null>("get_study_material", { id }),
  updateMaterial: (input: UpdateStudyMaterialInput) => invokeDatabase<StudyMaterial>("update_study_material", { input }),
  setMaterialStatus: (id: string, status: Extract<StudyMaterialStatus, "ACTIVE" | "ARCHIVED">) => invokeDatabase<StudyMaterial>("set_study_material_status", { id, status }),
  removeMaterial: (id: string) => invokeDatabase<void>("remove_study_material", { id }),
  deleteManagedMaterialFile: (id: string) => invokeDatabase<StudyMaterial>("delete_managed_study_material_file", { id }),
  associateMaterial: (materialId: string, input: StudyMaterialRelationInput) => invokeDatabase<StudyMaterialRelation[]>("associate_study_material", { materialId, input }),
  dissociateMaterial: (materialId: string, relationType: string, relationId: string) => invokeDatabase<StudyMaterialRelation[]>("dissociate_study_material", { materialId, relationType, relationId }),
  reprocessMaterialText: (id: string) => invokeDatabase<MaterialTextContent>("reprocess_study_material_text", { id }),
  previewMaterial: (id: string) => invokeDatabase<Uint8Array>("preview_study_material", { id }),
  openMaterial: (id: string) => invokeDatabase<void>("open_study_material", { id }),
};
