import { useMemo, useState } from "react";
import type { MarketAiDecisionLog, MarketAiRuntimeMetric, MarketExperimentResult, MarketRepeatabilityReport } from "../../types";
import { compareAiDecisions } from "./marketAiIntraday";

const pct = (value: number | null | undefined) => value == null ? "N/A" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`;

export function MarketAiIntradayComparison({ result, decisions, runtimes, repeatability, busy, onRepeat }: { result: MarketExperimentResult; decisions: MarketAiDecisionLog[]; runtimes: MarketAiRuntimeMetric[]; repeatability: MarketRepeatabilityReport | null; busy: boolean; onRepeat: () => void }) {
  const aiIds = result.experiment.agentIds.filter((id) => id.startsWith("ai-"));
  const [selectedAgent, setSelectedAgent] = useState(aiIds.includes("ai-intraday-v1") ? "ai-intraday-v1" : aiIds[0] ?? "");
  const selected = decisions.find((decision) => decision.agentId === selectedAgent && decision.callStatus !== "NO_LLM_CALL") ?? decisions.find((decision) => decision.agentId === selectedAgent);
  const comparison = useMemo(() => compareAiDecisions(aiIds, decisions), [aiIds, decisions]);
  if (!aiIds.includes("ai-intraday-v1")) return null;
  return <section className="market-ai-intraday">
    <div className="panel-heading"><strong>AI INTRADAY OBSERVATORY</strong><span>15M · CONTEXTO LOCAL · SEM EXECUÇÃO REAL</span></div>
    <div className="market-ai-intraday__agents">{aiIds.map((id) => { const runtime = runtimes.find((item) => item.agentId === id); const metric = result.metrics.find((item) => item.agentId === id); return <button key={id} className={selectedAgent === id ? "active" : ""} onClick={() => setSelectedAgent(id)}><span>{id === "ai-intraday-v1" ? "AI Intraday V1" : metric?.agentName ?? id}</span><b>{pct(metric?.totalReturnPct)}</b><small>{runtime?.promptVersion ?? "SEM RUNTIME"} · {runtime?.callCount ?? 0} CALLS · P95 {runtime?.p95LatencyMs ?? 0} ms</small></button>; })}</div>
    {comparison && <div className="market-ai-intraday__comparison"><div><span>OPORTUNIDADES COMPARÁVEIS</span><strong>{comparison.opportunities}</strong></div><div><span>DISCORDÂNCIAS</span><strong>{comparison.disagreements}</strong></div><div><span>DISAGREEMENT RATE</span><strong>{comparison.rate.toFixed(1)}%</strong></div><div><span>PAIR</span><strong>{comparison.left.replace("ai-", "")} / {comparison.right.replace("ai-", "")}</strong></div></div>}
    {selected && <div className="market-ai-intraday__inspector"><div><span>DECISION INSPECTOR</span><strong>{selected.timestamp}</strong><small>{selected.agentId} · {selected.callStatus}</small></div><dl><div><dt>INTENT / ACTION</dt><dd>{selected.intent ?? "N/A"} / {selected.action}</dd></div><div><dt>CONFIDENCE</dt><dd>{selected.confidence == null ? "N/A" : `${(selected.confidence * 100).toFixed(0)}%`}</dd></div><div><dt>REASON CODE</dt><dd>{selected.reasonCode ?? "N/A"}</dd></div><div><dt>RISK / EXECUTION</dt><dd>{selected.riskResult} / {selected.executionPrice?.toFixed(4) ?? "NO ORDER"}</dd></div><div><dt>CONTEXT / TRIGGER</dt><dd>{selected.contextVersion ?? "LEGACY"} / {selected.triggerVersion ?? "LEGACY"}</dd></div><div><dt>MODEL / TEMP / SEED</dt><dd>{selected.model} / {selected.temperature ?? "N/A"} / {selected.randomSeed ?? "N/A"}</dd></div><div><dt>CONTEXT SIZE</dt><dd>{selected.contextBytes ?? 0} bytes</dd></div><div><dt>FORWARD 1 / 5 / 10</dt><dd>{pct(selected.forwardReturn1)} / {pct(selected.forwardReturn5)} / {pct(selected.forwardReturn10)}</dd></div></dl><p>{selected.reason}</p><details><summary>CONTEXTO SERIALIZADO</summary><pre>{JSON.stringify(selected.inputSnapshot, null, 2)}</pre></details></div>}
    <div className="market-ai-intraday__repeat"><button className="button" disabled={busy} onClick={onRepeat}>{busy ? "EXECUTANDO N=3..." : "EXECUTAR REPEATABILITY · N=3"}</button><small>Ação manual. Cria três experimentos independentes com a configuração congelada.</small></div>
    {repeatability && <div className="market-ai-intraday__repeat-report"><strong>{repeatability.name}</strong>{repeatability.metrics.map((metric) => <div key={metric.agentId}><span>{metric.agentName}</span><b>RET {pct(metric.returnMeanPct)} · MIN {pct(metric.returnMinPct)} · MAX {pct(metric.returnMaxPct)} · σ {metric.returnStdPct.toFixed(3)}</b><small>DD médio {metric.drawdownMeanPct.toFixed(2)}% · calls {metric.callCountMean.toFixed(1)} · E/H/R/X {metric.enterCount}/{metric.holdCount}/{metric.reduceCount}/{metric.exitCount}</small></div>)}</div>}
  </section>;
}
